PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS organizations(id TEXT PRIMARY KEY,name TEXT NOT NULL,slug TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS properties(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),name TEXT NOT NULL,city TEXT NOT NULL,timezone TEXT NOT NULL DEFAULT 'Asia/Tashkent',is_active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS units(id TEXT PRIMARY KEY,property_id TEXT NOT NULL REFERENCES properties(id),code TEXT NOT NULL,name TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'available',capacity INTEGER NOT NULL DEFAULT 2,bedrooms INTEGER NOT NULL DEFAULT 1,UNIQUE(property_id,code));
CREATE TABLE IF NOT EXISTS app_users(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),email TEXT NOT NULL,display_name TEXT NOT NULL,is_active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(organization_id,email));
CREATE TABLE IF NOT EXISTS staff_roles(user_id TEXT NOT NULL REFERENCES app_users(id),property_id TEXT NOT NULL REFERENCES properties(id),role TEXT NOT NULL,PRIMARY KEY(user_id,property_id,role));
CREATE TABLE IF NOT EXISTS guests(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),user_id TEXT,first_name TEXT NOT NULL,last_name TEXT NOT NULL,email TEXT,phone TEXT,vip INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS reservations(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),property_id TEXT NOT NULL REFERENCES properties(id),unit_id TEXT REFERENCES units(id),primary_guest_id TEXT NOT NULL REFERENCES guests(id),confirmation_code TEXT NOT NULL UNIQUE,status TEXT NOT NULL,check_in_date TEXT NOT NULL,check_out_date TEXT NOT NULL,total_amount REAL,currency TEXT NOT NULL DEFAULT 'USD',version INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS service_orders(id TEXT PRIMARY KEY,organization_id TEXT NOT NULL REFERENCES organizations(id),property_id TEXT NOT NULL REFERENCES properties(id),unit_id TEXT REFERENCES units(id),guest_id TEXT REFERENCES guests(id),reservation_id TEXT REFERENCES reservations(id),stay_id TEXT,assigned_user_id TEXT,source TEXT NOT NULL,category TEXT NOT NULL,title TEXT NOT NULL,description TEXT,status TEXT NOT NULL DEFAULT 'new',priority TEXT NOT NULL DEFAULT 'normal',sla_due_at TEXT,service_amount REAL,service_cost REAL,currency TEXT NOT NULL DEFAULT 'USD',proof_metadata TEXT,idempotency_key TEXT NOT NULL UNIQUE,version INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_service_orders_property_status ON service_orders(property_id,status,created_at);
CREATE INDEX IF NOT EXISTS idx_service_orders_assignee ON service_orders(assigned_user_id,status,created_at);
CREATE TABLE IF NOT EXISTS service_order_events(id TEXT PRIMARY KEY,service_order_id TEXT NOT NULL REFERENCES service_orders(id),event_type TEXT NOT NULL,from_status TEXT,to_status TEXT,actor_user_id TEXT,actor_guest_id TEXT,payload TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS housekeeping_jobs(id TEXT PRIMARY KEY,property_id TEXT NOT NULL REFERENCES properties(id),unit_id TEXT NOT NULL REFERENCES units(id),reservation_id TEXT REFERENCES reservations(id),assigned_user_id TEXT,status TEXT NOT NULL DEFAULT 'open',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,started_at TEXT,completed_at TEXT,verified_at TEXT);
CREATE TABLE IF NOT EXISTS maintenance_tickets(id TEXT PRIMARY KEY,property_id TEXT NOT NULL REFERENCES properties(id),unit_id TEXT REFERENCES units(id),assigned_user_id TEXT,title TEXT NOT NULL,description TEXT,priority TEXT NOT NULL DEFAULT 'normal',status TEXT NOT NULL DEFAULT 'open',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,resolved_at TEXT);
CREATE TABLE IF NOT EXISTS audit_log(id TEXT PRIMARY KEY,organization_id TEXT,actor_user_id TEXT,entity_type TEXT NOT NULL,entity_id TEXT,action TEXT NOT NULL,before_state TEXT,after_state TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS outbox_events(id TEXT PRIMARY KEY,organization_id TEXT,event_type TEXT NOT NULL,aggregate_type TEXT NOT NULL,aggregate_id TEXT NOT NULL,idempotency_key TEXT NOT NULL UNIQUE,payload TEXT NOT NULL,processed_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

INSERT OR IGNORE INTO organizations(id,name,slug) VALUES('views','VIEWS Hotel & Apartments','views');
INSERT OR IGNORE INTO properties(id,organization_id,name,city) VALUES('utower','views','NRG U-Tower','Tashkent');
