import test from "node:test";
import assert from "node:assert/strict";
import {Pool} from "pg";
import {randomUUID} from "node:crypto";
import {inTenantTransaction} from "../src/postgres.mjs";
import {updateAssignedTask} from "../src/dispatch.mjs";
import {initializeCleaningChecklist,completeCleaningItem,finalizeCleaningTask,registerLaundryBag,transitionLaundryBag} from "../src/cleaning-laundry.mjs";
if(!process.env.TEST_DATABASE_URL)throw Error("TEST_DATABASE_URL required");
const pool=new Pool({connectionString:process.env.TEST_DATABASE_URL});
test("cleaning checklist is immutable and must be completed by assignee",async()=>{
 const org=randomUUID(),property=randomUUID(),orderId=randomUUID(),taskId=randomUUID();
 await inTenantTransaction(pool,org,async db=>{
  await db.query("INSERT INTO service_orders(id,organization_id,property_id,service_type,idempotency_key,fulfillment_status) VALUES($1,$2,$3,'cleaning',$4,'confirmed')",[orderId,org,property,"clean-"+randomUUID()]);
  await db.query("INSERT INTO service_property_access(organization_id,property_id,principal_id,permission) VALUES($1,$2,'manager','order:manage')",[org,property]);
  await db.query("INSERT INTO service_task_assignees(organization_id,property_id,principal_id) VALUES($1,$2,$3)",[org,property,"cleaner"]);
  await db.query("INSERT INTO service_dispatch_tasks(id,organization_id,order_id,property_id,task_kind,assigned_principal_id,status) VALUES($1,$2,$3,$4,'cleaning','cleaner','in_progress')",[taskId,org,orderId,property]);
 });
 const context={organizationId:org,taskId};
 await assert.rejects(initializeCleaningChecklist(pool,{...context,actorId:"manager",items:[{code:"bath",label:"Bathroom"}]}),/not editable/);
 await inTenantTransaction(pool,org,db=>db.query("UPDATE service_dispatch_tasks SET status='assigned' WHERE id=$1",[taskId]));
 await initializeCleaningChecklist(pool,{...context,actorId:"manager",items:[{code:"bath",label:"Bathroom"},{code:"bed",label:"Bed"}]});
 await assert.rejects(initializeCleaningChecklist(pool,{...context,actorId:"manager",items:[{code:"x",label:"Test"}]}),/already initialized/);
 await inTenantTransaction(pool,org,db=>db.query("UPDATE service_dispatch_tasks SET status='in_progress' WHERE id=$1",[taskId]));
 await assert.rejects(completeCleaningItem(pool,{...context,actorId:"intruder",itemCode:"bath"}),/Forbidden/);
 await completeCleaningItem(pool,{...context,actorId:"cleaner",itemCode:"bath"});
 await assert.rejects(finalizeCleaningTask(pool,{...context,actorId:"cleaner"}),/Checklist incomplete/);
 await assert.rejects(updateAssignedTask(pool,{organizationId:org,taskId,actorId:"cleaner",nextStatus:"completed"}),/Cleaning checklist required/);
 await completeCleaningItem(pool,{...context,actorId:"cleaner",itemCode:"bed"});
 const finished=await finalizeCleaningTask(pool,{...context,actorId:"cleaner"});
 assert.equal(finished.status,"completed");
 const accrual=await accrueTaskCompensation(pool,{organizationId:org,taskId,actorId:"manager",amountUzs:25000});
 assert.equal(accrual.status,"accrued");
 const replay=await accrueTaskCompensation(pool,{organizationId:org,taskId,actorId:"manager",amountUzs:25000});
 assert.equal(replay.id,accrual.id);
 await assert.rejects(accrueTaskCompensation(pool,{organizationId:org,taskId,actorId:"manager",amountUzs:30000}),/Accrual conflict/);
 await assert.rejects(approveTaskCompensation(pool,{organizationId:org,accrualId:accrual.id,actorId:"cleaner"}),/Forbidden/);
 const approved=await approveTaskCompensation(pool,{organizationId:org,accrualId:accrual.id,actorId:"manager"});
 assert.equal(approved.status,"approved");
 await assert.rejects(approveTaskCompensation(pool,{organizationId:org,accrualId:accrual.id,actorId:"manager"}),/already processed/);
 await assert.rejects(finalizeCleaningTask(pool,{...context,actorId:"cleaner"}),/Forbidden/);
 const hidden=await inTenantTransaction(pool,randomUUID(),async db=>(await db.query("SELECT id FROM service_cleaning_checklist_items WHERE task_id=$1",[taskId])).rows);
 assert.equal(hidden.length,0);
});
test("laundry custody records ordered transitions and rejects foreign actor",async()=>{
 const org=randomUUID(),property=randomUUID(),orderId=randomUUID();
 await inTenantTransaction(pool,org,async db=>{
  await db.query("INSERT INTO service_orders(id,organization_id,property_id,service_type,idempotency_key,fulfillment_status) VALUES($1,$2,$3,'laundry',$4,'confirmed')",[orderId,org,property,"laundry-"+randomUUID()]);
  await db.query("INSERT INTO service_property_access(organization_id,property_id,principal_id,permission) VALUES($1,$2,'manager','order:manage')",[org,property]);
 });
 const bag=await registerLaundryBag(pool,{organizationId:org,orderId,actorId:"manager",bagCode:"BAG-"+randomUUID(),itemCount:5});
 assert.equal(bag.status,"registered");
 await assert.rejects(transitionLaundryBag(pool,{organizationId:org,bagId:bag.id,actorId:"outsider",nextStatus:"collected"}),/Forbidden/);
 await assert.rejects(transitionLaundryBag(pool,{organizationId:org,bagId:bag.id,actorId:"manager",nextStatus:"returned"}),/Invalid laundry transition/);
 for(const status of ["collected","processing","ready","returned"])await transitionLaundryBag(pool,{organizationId:org,bagId:bag.id,actorId:"manager",nextStatus:status});
 const state=await inTenantTransaction(pool,org,async db=>(await db.query("SELECT status,received_by,returned_by FROM service_laundry_bags WHERE id=$1",[bag.id])).rows[0]);
 assert.deepEqual(state,{status:"returned",received_by:"manager",returned_by:"manager"});
 const events=await inTenantTransaction(pool,org,async db=>(await db.query("SELECT count(*)::integer AS n FROM service_laundry_bag_events WHERE bag_id=$1",[bag.id])).rows[0]);
 assert.equal(events.n,5);
});
test.after(async()=>pool.end());
