import test from "node:test";
import assert from "node:assert/strict";
import {once} from "node:events";
import {createHmac,randomUUID} from "node:crypto";
import {inTenantTransaction} from "../src/postgres.mjs";

if(!process.env.TEST_DATABASE_URL)throw Error("TEST_DATABASE_URL required");
if(!process.env.VIEWS_AUTH_SECRET||process.env.VIEWS_AUTH_SECRET.length<32)throw Error("VIEWS_AUTH_SECRET required");
process.env.DATABASE_URL=process.env.TEST_DATABASE_URL;
process.env.VIEWS_ALLOW_DEV_AUTH="1";
const {server,pool}=await import("../src/db-server.mjs");
const sign=(organizationId,sub,roles)=>{
 const body=Buffer.from(JSON.stringify({organizationId,sub,roles,exp:Math.floor(Date.now()/1000)+600})).toString("base64url");
 return body+"."+createHmac("sha256",process.env.VIEWS_AUTH_SECRET).update(body).digest("base64url");
};
test("CRM serves assets, enforces roles, and cancels reserved order",async()=>{
 const org=randomUUID(),property=randomUUID(),bookingId=randomUUID(),staff="crm-integration-staff";
 await inTenantTransaction(pool,org,async db=>{
  await db.query("INSERT INTO market_catalog(organization_id,sku,name,price_uzs) VALUES($1,$2,$3,$4)",[org,"WATER-15","Вода 1,5 л",15000]);
  await db.query("INSERT INTO service_property_access(organization_id,property_id,principal_id,permission) VALUES($1,$2,$3,'order:create'),($1,$2,$3,'order:manage')",[org,property,staff]);
  await db.query("INSERT INTO inventory_lots(organization_id,sku,on_hand,reserved) VALUES($1,'WATER-15',5,0)",[org]);
  await db.query("INSERT INTO service_guest_bookings(id,organization_id,property_id,guest_principal_id,status,starts_at,ends_at) VALUES($1,$2,$3,$4,'checked_in',now()-interval '1 day',now()+interval '1 day')",[bookingId,org,property,"guest-1"]);
 });
 server.listen(0,"127.0.0.1");
 await once(server,"listening");
 const base="http://127.0.0.1:"+server.address().port;
 const staffToken=sign(org,staff,["dispatcher"]),guestToken=sign(org,"guest-1",["guest"]);
 try{
  const staffPage=await fetch(base+"/staff");
  assert.equal(staffPage.status,200);
  assert.match(await staffPage.text(),/staff\.css/);
  const staffScript=await fetch(base+"/staff.js");
  assert.equal(staffScript.status,200);
  const staffStyles=await fetch(base+"/staff.css");
  assert.equal(staffStyles.status,200);
  const page=await fetch(base+"/crm");
  assert.equal(page.status,200);
  assert.match(await page.text(),/crm\.css/);
  assert.match(page.headers.get("content-security-policy"),/style-src 'self'/);
  const stylesheet=await fetch(base+"/crm.css");
  assert.equal(stylesheet.status,200);
  assert.match(stylesheet.headers.get("content-type"),/text\/css/);
  const session=await fetch(base+"/api/v1/me",{headers:{Authorization:"Bearer "+staffToken}});
  assert.equal(session.status,200);
  const identity=await session.json();
  assert.deepEqual(identity,{sub:staff,organizationId:org,roles:["dispatcher"],authMode:"dev"});
  const noSession=await fetch(base+"/api/v1/me");
  assert.equal(noSession.status,401);
  const unauthorized=await fetch(base+"/api/v1/service-orders");
  assert.equal(unauthorized.status,401);
  const forbidden=await fetch(base+"/api/v1/service-orders",{headers:{Authorization:"Bearer "+guestToken}});
  assert.equal(forbidden.status,403);
  const catalog=await fetch(base+"/api/v1/market/catalog",{headers:{Authorization:"Bearer "+guestToken}});
  assert.equal(catalog.status,200);
  assert.equal((await catalog.json())[0].priceUzs,15000);
  const myBookings=await fetch(base+"/api/v1/me/bookings",{headers:{Authorization:"Bearer "+guestToken}});
  assert.equal(myBookings.status,200);
  assert.ok((await myBookings.json()).some(b=>b.id===bookingId));
  const missingBooking=await fetch(base+"/api/v1/service-orders",{method:"POST",headers:{"content-type":"application/json",Authorization:"Bearer "+guestToken,"Idempotency-Key":"missing-"+randomUUID()},body:JSON.stringify({items:[{sku:"WATER-15",quantity:1}]})});
  assert.equal(missingBooking.status,422);
  const expiredBooking=randomUUID();
  await inTenantTransaction(pool,org,async db=>db.query("INSERT INTO service_guest_bookings(id,organization_id,property_id,guest_principal_id,status,starts_at,ends_at) VALUES($1,$2,$3,$4,'checked_out',now()-interval '3 days',now()-interval '1 day')",[expiredBooking,org,property,"guest-1"]));
  const expiredOrder=await fetch(base+"/api/v1/service-orders",{method:"POST",headers:{"content-type":"application/json",Authorization:"Bearer "+guestToken,"Idempotency-Key":"expired-"+randomUUID()},body:JSON.stringify({bookingId:expiredBooking,items:[{sku:"WATER-15",quantity:1}]})});
  assert.equal(expiredOrder.status,403);
  const guestOrderResponse=await fetch(base+"/api/v1/service-orders",{method:"POST",headers:{"content-type":"application/json",Authorization:"Bearer "+guestToken,"Idempotency-Key":"guest-"+randomUUID()},body:JSON.stringify({bookingId,items:[{sku:"WATER-15",quantity:1}]})});
  assert.equal(guestOrderResponse.status,201);
  const guestOrder=await guestOrderResponse.json();
  const guestHistory=await fetch(base+"/api/v1/me/orders",{headers:{Authorization:"Bearer "+guestToken}});
  assert.equal(guestHistory.status,200);
  const ownHistory=await guestHistory.json();
  assert.ok(ownHistory.some(row=>row.id===guestOrder.id));
  assert.ok(ownHistory.every(row=>row.id===guestOrder.id));
  const foreignHistory=await fetch(base+"/api/v1/me/orders",{headers:{Authorization:"Bearer "+sign(org,"other-guest",["guest"])}});
  assert.equal(foreignHistory.status,200);
  assert.deepEqual(await foreignHistory.json(),[]);
  const otherTenantHistory=await fetch(base+"/api/v1/me/orders",{headers:{Authorization:"Bearer "+sign(randomUUID(),"guest-1",["guest"])}});
  assert.equal(otherTenantHistory.status,200);
  assert.deepEqual(await otherTenantHistory.json(),[]);
  const unauthHistory=await fetch(base+"/api/v1/me/orders");
  assert.equal(unauthHistory.status,401);
  const staffHistory=await fetch(base+"/api/v1/me/orders",{headers:{Authorization:"Bearer "+staffToken}});
  assert.equal(staffHistory.status,403);
  await inTenantTransaction(pool,org,async db=>db.query(
   "INSERT INTO service_outbox(organization_id,aggregate_id,event_type,payload) VALUES($1,$2,'service.task.assigned',$3::jsonb)",
   [org,guestOrder.id,JSON.stringify({orderId:guestOrder.id,kind:"market_deliver",assigneeId:"private-employee-identifier"})]));
  const notifications=await fetch(base+"/api/v1/me/notifications",{headers:{Authorization:"Bearer "+guestToken}});
  assert.equal(notifications.status,200);
  const inbox=await notifications.json();
  assert.ok(inbox.some(n=>n.order_id===guestOrder.id&&n.message==="Назначена доставка"));
  assert.ok(!JSON.stringify(inbox).includes("private-employee-identifier"));
  const again=await fetch(base+"/api/v1/me/notifications",{headers:{Authorization:"Bearer "+guestToken}});
  assert.equal(again.status,200);
  assert.equal((await again.json()).length,inbox.length);
  const notification=inbox.find(n=>n.message==="Назначена доставка");
  const deniedRead=await fetch(base+"/api/v1/me/notifications/"+notification.id+"/read",{method:"POST",headers:{Authorization:"Bearer "+sign(org,"other-guest",["guest"])}});
  assert.equal(deniedRead.status,404);
  const crossTenantRead=await fetch(base+"/api/v1/me/notifications/"+notification.id+"/read",{method:"POST",headers:{Authorization:"Bearer "+sign(randomUUID(),"guest-1",["guest"])}});
  assert.equal(crossTenantRead.status,404);
  const marked=await fetch(base+"/api/v1/me/notifications/"+notification.id+"/read",{method:"POST",headers:{Authorization:"Bearer "+guestToken}});
  assert.equal(marked.status,200);
  const firstRead=await marked.json();
  assert.ok(firstRead.read_at);
  const markedAgain=await fetch(base+"/api/v1/me/notifications/"+notification.id+"/read",{method:"POST",headers:{Authorization:"Bearer "+guestToken}});
  assert.equal((await markedAgain.json()).read_at,firstRead.read_at);
  const staffNotifications=await fetch(base+"/api/v1/me/notifications",{headers:{Authorization:"Bearer "+staffToken}});
  assert.equal(staffNotifications.status,403);
  const guestTimeline=await fetch(base+"/api/v1/me/orders/"+guestOrder.id+"/timeline",{headers:{Authorization:"Bearer "+guestToken}});
  assert.equal(guestTimeline.status,200);
  const timelineEvents=await guestTimeline.json();
  assert.ok(timelineEvents.some(e=>e.type==="market.order.created"));
  assert.ok(timelineEvents.some(e=>e.type==="service.task.assigned"&&e.taskKind==="market_deliver"));
  assert.ok(!JSON.stringify(timelineEvents).includes("private-employee-identifier"));
  const foreignTimeline=await fetch(base+"/api/v1/me/orders/"+guestOrder.id+"/timeline",{headers:{Authorization:"Bearer "+sign(org,"other-guest",["guest"])}});
  assert.equal(foreignTimeline.status,404);
  const tenantTimeline=await fetch(base+"/api/v1/me/orders/"+guestOrder.id+"/timeline",{headers:{Authorization:"Bearer "+sign(randomUUID(),"guest-1",["guest"])}});
  assert.equal(tenantTimeline.status,404);
  const staffTimeline=await fetch(base+"/api/v1/me/orders/"+guestOrder.id+"/timeline",{headers:{Authorization:"Bearer "+staffToken}});
  assert.equal(staffTimeline.status,403);
  const owned=await fetch(base+"/api/v1/service-orders/"+guestOrder.id,{headers:{Authorization:"Bearer "+guestToken}});
  assert.equal(owned.status,200);
  const foreignGuestToken=sign(org,"other-guest",["guest"]);
  const foreign=await fetch(base+"/api/v1/service-orders/"+guestOrder.id,{headers:{Authorization:"Bearer "+foreignGuestToken}});
  assert.equal(foreign.status,404);
  const foreignCreate=await fetch(base+"/api/v1/service-orders",{method:"POST",headers:{"content-type":"application/json",Authorization:"Bearer "+foreignGuestToken,"Idempotency-Key":"foreign-"+randomUUID()},body:JSON.stringify({bookingId,items:[{sku:"WATER-15",quantity:1}]})});
  assert.equal(foreignCreate.status,403);
  const key="http-"+randomUUID();
  const request={method:"POST",headers:{"content-type":"application/json",Authorization:"Bearer "+staffToken,"Idempotency-Key":key},body:JSON.stringify({propertyId:property,items:[{sku:"WATER-15",quantity:2}]})};
  const created=await fetch(base+"/api/v1/service-orders",request);
  assert.equal(created.status,201);
  const order=await created.json();
  const storedPrice=await inTenantTransaction(pool,org,async db=>(await db.query("SELECT total_uzs,delivery_fee_uzs FROM service_orders WHERE id=$1",[order.id])).rows[0]);
  assert.equal(Number(storedPrice.total_uzs),45000);
  assert.equal(Number(storedPrice.delivery_fee_uzs),15000);
  const snapshot=await inTenantTransaction(pool,org,async db=>(await db.query("SELECT unit_price_uzs FROM service_order_items WHERE order_id=$1",[order.id])).rows[0]);
  assert.equal(Number(snapshot.unit_price_uzs),15000);
  await inTenantTransaction(pool,org,async db=>db.query("UPDATE market_catalog SET price_uzs=$1 WHERE organization_id=$2 AND sku=$3",[19000,org,"WATER-15"]));
  const originalSnapshot=await inTenantTransaction(pool,org,async db=>(await db.query("SELECT unit_price_uzs FROM service_order_items WHERE order_id=$1",[order.id])).rows[0]);
  assert.equal(Number(originalSnapshot.unit_price_uzs),15000);
  const unrelatedDispatcher=sign(org,"dispatcher-without-property",["dispatcher"]);
  const unrelatedList=await fetch(base+"/api/v1/service-orders",{headers:{Authorization:"Bearer "+unrelatedDispatcher}});
  assert.equal(unrelatedList.status,200);
  assert.equal((await unrelatedList.json()).length,0);
  const unrelatedRead=await fetch(base+"/api/v1/service-orders/"+order.id,{headers:{Authorization:"Bearer "+unrelatedDispatcher}});
  assert.equal(unrelatedRead.status,404);
  const unrelatedUpdate=await fetch(base+"/api/v1/service-orders/"+order.id,{method:"PATCH",headers:{"content-type":"application/json",Authorization:"Bearer "+unrelatedDispatcher},body:JSON.stringify({fulfillmentStatus:"cancelled"})});
  assert.equal(unrelatedUpdate.status,403);
  const adminToken=sign(org,"test-admin",["admin"]);
  const adminList=await fetch(base+"/api/v1/service-orders",{headers:{Authorization:"Bearer "+adminToken}});
  assert.ok((await adminList.json()).some(x=>x.id===order.id));
  await inTenantTransaction(pool,org,async db=>db.query("INSERT INTO service_task_assignees(organization_id,property_id,principal_id) VALUES($1,$2,$3)",[org,property,"picker-1"]));
  const assigned=await fetch(base+"/api/v1/dispatch/assign",{method:"POST",headers:{"content-type":"application/json",Authorization:"Bearer "+staffToken},body:JSON.stringify({orderId:order.id,assigneeId:"picker-1",kind:"market_pick"})});
  assert.equal(assigned.status,201);
  const assignedTask=await assigned.json();
  assert.equal(assignedTask.assigneeId,"picker-1");
  const cleaningTaskId=randomUUID();
  await inTenantTransaction(pool,org,async db=>{
   await db.query("INSERT INTO service_dispatch_tasks(id,organization_id,order_id,property_id,task_kind,assigned_principal_id,status) VALUES($1,$2,$3,$4,'cleaning','picker-1','in_progress')",[cleaningTaskId,org,order.id,property]);
   await db.query("INSERT INTO service_cleaning_checklist_items(organization_id,task_id,item_code,label) VALUES($1,$2,'bathroom','Ванная')",[org,cleaningTaskId]);
  });
  const pickerToken=sign(org,"picker-1",["staff"]);
  const checklist=await fetch(base+"/api/v1/staff/tasks/"+cleaningTaskId+"/checklist",{headers:{Authorization:"Bearer "+pickerToken}});
  assert.equal(checklist.status,200);
  assert.equal((await checklist.json())[0].item_code,"bathroom");
  const foreignChecklist=await fetch(base+"/api/v1/staff/tasks/"+cleaningTaskId+"/checklist",{headers:{Authorization:"Bearer "+sign(org,"another-worker",["staff"])}});
  assert.equal(foreignChecklist.status,403);
  const myTasks=await fetch(base+"/api/v1/staff/tasks",{headers:{Authorization:"Bearer "+pickerToken}});
  assert.equal(myTasks.status,200);
  assert.ok((await myTasks.json()).some(t=>t.id===assignedTask.id));
  const notMine=await fetch(base+"/api/v1/staff/tasks/"+assignedTask.id,{method:"PATCH",headers:{"content-type":"application/json",Authorization:"Bearer "+sign(org,"another-worker",["staff"])},body:JSON.stringify({status:"in_progress"})});
  assert.equal(notMine.status,403);
  const started=await fetch(base+"/api/v1/staff/tasks/"+assignedTask.id,{method:"PATCH",headers:{"content-type":"application/json",Authorization:"Bearer "+pickerToken},body:JSON.stringify({status:"in_progress"})});
  assert.equal(started.status,200);
  const regress=await fetch(base+"/api/v1/dispatch/assign",{method:"POST",headers:{"content-type":"application/json",Authorization:"Bearer "+staffToken},body:JSON.stringify({orderId:order.id,assigneeId:"picker-1",kind:"market_pick"})});
  assert.equal(regress.status,409);
  const completed=await fetch(base+"/api/v1/staff/tasks/"+assignedTask.id,{method:"PATCH",headers:{"content-type":"application/json",Authorization:"Bearer "+pickerToken},body:JSON.stringify({status:"completed"})});
  assert.equal(completed.status,200);
  const repeated=await fetch(base+"/api/v1/staff/tasks/"+assignedTask.id,{method:"PATCH",headers:{"content-type":"application/json",Authorization:"Bearer "+pickerToken},body:JSON.stringify({status:"completed"})});
  assert.equal(repeated.status,409);

  const deliveryAssignment=await fetch(base+"/api/v1/dispatch/assign",{method:"POST",headers:{"content-type":"application/json",Authorization:"Bearer "+staffToken},body:JSON.stringify({orderId:order.id,assigneeId:"picker-1",kind:"market_deliver"})});
  assert.equal(deliveryAssignment.status,201);
  const deliveryTask=await deliveryAssignment.json();
  const sla=await fetch(base+"/api/v1/dispatch/sla",{headers:{Authorization:"Bearer "+staffToken}});
  assert.equal(sla.status,200);
  const summary=await sla.json();
  assert.ok(summary.total>=2);
  const deniedSla=await fetch(base+"/api/v1/dispatch/sla",{headers:{Authorization:"Bearer "+sign(org,"guest-1",["guest"])}});
  assert.equal(deniedSla.status,403);
  const hiddenSla=await fetch(base+"/api/v1/dispatch/sla",{headers:{Authorization:"Bearer "+unrelatedDispatcher}});
  assert.equal((await hiddenSla.json()).total,0);
  const staffTasks=await fetch(base+"/api/v1/dispatch/tasks",{headers:{Authorization:"Bearer "+staffToken}});
  assert.ok((await staffTasks.json()).some(t=>t.id===assignedTask.id));
  const unauthorizedTasks=await fetch(base+"/api/v1/dispatch/tasks",{headers:{Authorization:"Bearer "+unrelatedDispatcher}});
  assert.deepEqual(await unauthorizedTasks.json(),[]);
  const deniedAssign=await fetch(base+"/api/v1/dispatch/assign",{method:"POST",headers:{"content-type":"application/json",Authorization:"Bearer "+unrelatedDispatcher},body:JSON.stringify({orderId:order.id,assigneeId:"picker-1"})});
  assert.equal(deniedAssign.status,403);
  const guestRead=await fetch(base+"/api/v1/service-orders/"+order.id,{headers:{Authorization:"Bearer "+guestToken}});
  assert.equal(guestRead.status,404);
  const staffRead=await fetch(base+"/api/v1/service-orders/"+order.id,{headers:{Authorization:"Bearer "+staffToken}});
  assert.equal(staffRead.status,200);
  const guestPage=await fetch(base+"/guest");
  assert.equal(guestPage.status,200);
  const guestJs=await fetch(base+"/guest.js");
  assert.equal(guestJs.status,200);
  const replay=await fetch(base+"/api/v1/service-orders",request);
  assert.equal(replay.status,200);
  assert.equal((await replay.json()).id,order.id);
  const listed=await fetch(base+"/api/v1/service-orders",{headers:{Authorization:"Bearer "+staffToken}});
  assert.equal(listed.status,200);
  assert.ok((await listed.json()).some(x=>x.id===order.id));
  const cancelled=await fetch(base+"/api/v1/service-orders/"+order.id,{method:"PATCH",headers:{"content-type":"application/json",Authorization:"Bearer "+staffToken},body:JSON.stringify({fulfillmentStatus:"cancelled"})});
  assert.equal(cancelled.status,200);
  assert.equal((await cancelled.json()).fulfillmentStatus,"cancelled");
  const cancelledTask=await inTenantTransaction(pool,org,async db=>(await db.query("SELECT status FROM service_dispatch_tasks WHERE id=$1",[assignedTask.id])).rows[0]);
  assert.equal(cancelledTask.status,"completed");
  const cancelledDelivery=await inTenantTransaction(pool,org,async db=>(await db.query("SELECT status FROM service_dispatch_tasks WHERE id=$1",[deliveryTask.id])).rows[0]);
  assert.equal(cancelledDelivery.status,"cancelled");
  const cancelGuest=await fetch(base+"/api/v1/service-orders/"+guestOrder.id,{method:"PATCH",headers:{"content-type":"application/json",Authorization:"Bearer "+staffToken},body:JSON.stringify({fulfillmentStatus:"cancelled"})});
  assert.equal(cancelGuest.status,200);
  const inventory=await inTenantTransaction(pool,org,async db=>(await db.query("SELECT on_hand,reserved FROM inventory_lots WHERE organization_id=$1 AND sku='WATER-15'",[org])).rows[0]);
  assert.deepEqual(inventory,{on_hand:5,reserved:0});
 }finally{
  await new Promise((resolve,reject)=>server.close(err=>err?reject(err):resolve()));
  await pool.end();
 }
});
