plugins { id 'com.android.application' }
android {
    namespace 'uz.views.development'
    compileSdk 35
    defaultConfig {
        applicationId 'uz.views.development'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.1.0-dev'
    }
    buildTypes {
        debug { debuggable true }
        release { minifyEnabled false }
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
